### ISSUE TITLE
[question] How can we develop with qgis-server?

### ISSUE THREAD

**Issue by Kanahiro** [bbox-services/bbox#69]
Hello,
Thank you for developing this great software. I believe this is one of the most exciting server implementation among recent FOSS4G.

I've tried to edit some codes in this repository and found `bbox-map-server` depends on qgis-server/umn-map-server of a host machine (and only on Linux?).

https://github.com/bbox-services/bbox/blob/94406fa57a20b1132f68bfbdeab84dd1875b3cb5/bbox-map-server/src/wms_fcgi_backend.rs#L49

 It is not unnatural and in container image those dependencies are clearly resolved, it's great. 

However, trying to develop, this is a problem for me.

I guess there might be some tips for developing with qgis-server conveniently.
If there is, could you tell me how to develop with qgis-server?

**Comment by pka** [comment]
Sorry, missed that during holidays. 

The location of the QGIS Server location should be configurable: https://www.bbox.earth/map-server/reference.html#qgisbackend

Usage example:
```toml
[mapserver.qgis_backend]
exe_location = "/usr/local/cgi-bin/qgis_mapserv.fcgi"
```

But this is currently broken! Will fix it make a release in the coming days.

**Comment by pka** [comment]
0.6.0-beta1 with fix is released.
