### ISSUE TITLE
Error during initialization: invalid type: found map, expected a string for key "default.datasource.0" in bbox.toml TOML file

### ISSUE THREAD

**Issue by rduivenvoorde** [bbox-services/bbox#79]
Thank you for providing BBOX!

Trying to setup bbox as a featureserver, I get

`Error during initialization: invalid type: found map, expected a string for key "default.datasource.0" in bbox.toml TOML file`

Any hints on how to tackle this?

I tried to create a minimal config, but never get a working WFS...

Would it be possible to provide some more full working configs?
The config details in the docs are too rudimentary (at least for me :-) )
Or at least some general idea of what the toml should look like, or why.
Is there supposed to be some 'default datasource'?
Is the second part of 'datasource.postgis' in the examples a 'type', or an 'id'?
etc

```
[webserver]
server_addr = "0.0.0.0:8080"  # Default: 127.0.0.1:8080

[featureserver]

[[datasource]]
name = "test"

[[datasource.postgis]]
# export PGPASSWORD=test
url = "postgres://test@localhost:5432/test"

[[collection]]
name = "lastweek"
title = "lastweek"
description = "lastweek"
[collection.postgis]
datasource = "test"
table = "myschema.mytable"
```

**Comment by pka** [comment]
`datasource.postgis` is not an array, so has only single brackets:

```
[[datasource]]
name = "test"

[datasource.postgis]
url = "postgres://test@localhost:5432/test"
```

See also the example at https://www.bbox.earth/feature-server/configuration.html

The error message is not good, but not easy to improve.
