### ISSUE TITLE
Support for base href and configuration via public_server_url

### ISSUE THREAD

**Issue by FabianRechsteiner** [bbox-services/bbox#80]
**Description:**
There is an issue with the BBOX application when hosted in a subpath (e.g., /bbox). The `base href` parameter is missing in the generated HTML, causing links to point incorrectly. For instance, links point to `https://mydomain/collections` instead of `https://mydomain/bbox/collections`.

**Proposal:**

Integrate a `base href` parameter in the HTML files of the BBOX application to ensure the correct subpath is set.
Make the base href value configurable either through Docker Compose or the bbox.toml configuration file, for example, by using the already existing `public_server_url` parameter.
This change would resolve issues with broken links when using the application in a subpath.

Are there other approaches to solve this problem?

**Comment by pka** [comment]
Implemented in #86
